version: "3.5"
networks:
    default:
      external:
        name: setup_default

services:
    first-join:
        image: stream-transformer
        environment:
            BROKER: http://broker:29092
            SCHEMA_REGISTRY: http://schema-registry:8081
            OUTPUT_TOPIC: multi-join-test
            AUTO_OFFSET_RESET_CONFIG: earliest